spring:
  profiles:
    active:
    - dev
---
server:
  port: 8203
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/
---

server:
  port: 8204
spring:
  profiles: test
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka/